### ISSUE TITLE
Possible to use Domo with types defined not in a struct?

### ISSUE THREAD

**Issue by notproperlycut** [IvanRublev/Domo#19]
Hi. Love this library, thank you. I'm trying to use it with a commanded project, and spotted the [example](https://github.com/IvanRublev/bank-commanded-domo) linked in your documentation.

Is it (still) possible to use domo with types that are defined outside of a struct? I saw [this line](https://github.com/IvanRublev/bank-commanded-domo/blob/01abf3f6a1164f79393b8f86eafc9ebf99d637a6/lib/bank.ex#L7) in the example and I've been trying to get something similar to work.

[This repo](https://github.com/notproperlycut/domo-test) shows the behaviour I'm seeing - running my test or the dialyzer appears to succeed the first time, will fail the second time, and then won't start at all the third or subsequent times.

I'm new to typespecs and this library, so forgive me if I've missed something obvious. If this is a regression, l'm happy to help but would need a little guidance :)

**Comment by IvanRublev** [comment]
Hey,
Thanks for your report. That's a bug due to the wrong assumption that all previously compiled modules are automatically loaded into memory. I release the fix. Please, upgrade to [version 1.5.5](https://hex.pm/packages/domo/1.5.5).

**Comment by notproperlycut** [comment]
Oh, amazing. I will upgrade, thank you
