### ISSUE TITLE
`required_fields` regression in 1.5.16

### ISSUE THREAD

**Issue by kzemek** [IvanRublev/Domo#33]
### Environment

* Elixir version (elixir -v): 1.17.2
* Domo version (mix deps | grep domo | head -1): 1.5.16

### Actual behavior

I'm using the following module definition:
```elixir
defmodule RequiredTest do
  use Domo
  @enforce_keys [:required]
  defstruct [:required, :optional]
  @type t :: %__MODULE__{required: integer(), optional: integer() | nil}
end
```

In Domo 1.5.16, `RequiredTest.required_fields()` returns `[:required, :optional]`, causing downstream problems e.g. for changeset validation.

### Expected behavior

`RequiredTest.required_fields()` should return `[:required]` like it does in Domo 1.5.14

**Comment by IvanRublev** [comment]
Hey @kzemek, the bug is fixed in https://hex.pm/packages/domo/1.5.18 please check it out!

I wish you a warm Happy New Year celebrations 🎅

**Comment by kzemek** [comment]
Thank you, works like a charm!
