### ISSUE TITLE
Elixir 1.18 compile error: 'should be called from within the module defining a struct'

### ISSUE THREAD

**Issue by ftes** [IvanRublev/Domo#34]
### Environment

* Elixir version (elixir -v): `Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:14:14] [ds:14:14:10] [async-threads:1] [jit], Elixir 1.18.0 (compiled with Erlang/OTP 27)`
* Domo version (mix deps | grep domo | head -1): `domo 1.5.16`

### Actual behavior

Fails to compile module with domo in Elixir 1.18:

```ex
== Compilation error in file lib/my_struct.ex ==
** (CompileError) use Domo should be called from within the module defining a struct.
    (domo 1.5.16) lib/domo/raises.ex:183: Domo.Raises.maybe_raise_incorrect_placement!/1
    (stdlib 6.1) lists.erl:2151: :lists.foldl_1/3
    lib/my_struct.ex:5: (module)
```

### Expected behavior

Compile successfully in Elixir 1.18 just like in previous versions.

### Verbose output

Not required.

**Comment by vheathen** [comment]
Yes, we are having the same problem.

**Comment by IvanRublev** [comment]
Hey folks, thanks for the heads up.

Please give a try for the Domo version [1.5.17](https://hex.pm/packages/domo/1.5.17) it has improved compatibility with Elixir 1.18. 
 
Merry Christmas and Happy New Year 🎅
