### ISSUE TITLE
Ensure types for TypedStruct in Tests

### ISSUE THREAD

**Issue by iacobson** [IvanRublev/Domo#8]
I try to use now the library for the first time and I really like the idea.
I am using it together with TypedStruct and see some weird behaviour in the tests

### Environment

* Elixir version (elixir -v): 1.12.3
* Domo version (mix deps | grep domo | head -1): 1.3.4
* TypedStruct version (mix deps | grep typed_struct | head -1): 0.2.1

### Actual behavior

I have a module like (simplified)

```elixir
defmodule Entity do
  use TypedStruct
  use Domo

  typedstruct do
    field :meta, map(), default: %{}, enforce: true
  end 

  def config(data) do
    config = %{meta: data.meta}
    Entity.new!(config)
  end
end
```

In the iex console all works as expected, but when running the tests, I noticed some type inconsistencies. So I did a test.

I modified the typedstruct to take a wrong type

```elixir
  typedstruct do
    field :meta, String.t(), default: %{}, enforce: true
  end 
```

Again. In the console, running something like Entity.config(%{meta: %{k: :v}}) would fail, trying to respect the new String.t()

```
Invalid value %{hello: 1} for field :meta of %Faktor.Entity{}. Expected the value matching the <<_::_*8>> type.
```

But in tests, no change, all tests pass, and they are passing maps to the meta.

### Expected behavior

Expected the tests to fail when the type is not valid

Is there anything I'm missing regarding running tests?

**Comment by IvanRublev** [comment]
Hey, thanks for your feedback.
Can you, please, attach an example project to the issue? I'd like to see the test file

**Comment by iacobson** [comment]
I created a minimal example that can reproduce the issue. That was a good exercise as I discovered that the issue mentioned above happens only in specific conditions:
- having a `__using__` macro that `use Domo`

https://github.com/iacobson/domo_example


To see it in action you can run the tests 
- this will fail: https://github.com/iacobson/domo_example/blob/main/test/domo_example_test.exs#L19
- but if you remove this line https://github.com/iacobson/domo_example/blob/main/lib/domo_example.ex#L12, it will pass

In the iex console, everything works as expected

**Comment by IvanRublev** [comment]
Thanks for the example project. Turns out that it was a mistake in the runtime mode detection when any module using Domo was added to the test .exs file. That kind of scenario is unsupported and `Domo` of [version 1.4.0](https://hex.pm/packages/domo/1.4.0) raises an error about it.

To have structs using Domo specific to your test environment, add them into a separate directory and put the path to it in your mix.exs like the following:

```elixir
def project do
  ...
  elixirc_paths: elixirc_paths(Mix.env())
  ...
end

defp elixirc_paths(:test), do: ["lib", "test/support"]
defp elixirc_paths(_), do: ["lib"]
```

**Comment by iacobson** [comment]
Very nice, thanks!

So upgrading to 1.4.0 immediately raised the error.

Then I refactored as you suggested, and all works as expected.

This is the commit, in case anybody needs it:
https://github.com/iacobson/domo_example/commit/0625d13ddc48d340e76ba25163a4f68aafe3283a


From my point of view, I will close this issue.
